# Start with our mcgrath docker image
image: 4mation/wordpress:mcgrath

pipelines:
  branches:
    master:
      - step:
          deployment: production
          name: Build Artifact and Deploy to Production
          caches:
            - composer
            - yarn
            - node
          script:
            # Move code to our working directory & fix ownerships
            - cp -a $BITBUCKET_CLONE_DIR/. /home/wp/code && chown -R wp:wp /home/wp/
            # Build Assets
            - su -c "export WP_ENV=production; /home/wp/code/env/tools/initial-setup.sh" -s /bin/sh wp
            # Deploy to ElasticBeanstalk
            - su -c "export ENVIRONMENT='Production'; /home/wp/code/env/build/build-artifact.sh" -s /bin/sh wp
    uat-*:
      - step:
          deployment: test
          name: Build Artifact and Deploy to UAT
          caches:
            - composer
            - yarn
            - node
          script:
            # Move code to our working directory & fix ownerships
            - cp -a $BITBUCKET_CLONE_DIR/. /home/wp/code && chown -R wp:wp /home/wp/
            # Build Assets
            - su -c "export WP_ENV=uat; /home/wp/code/env/tools/initial-setup.sh" -s /bin/sh wp
            # Deploy to ElasticBeanstalk
            - su -c "export ENVIRONMENT='U-A-T'; /home/wp/code/env/build/build-artifact.sh" -s /bin/sh wp
    staging-*:
      - step:
          deployment: staging
          name: Build Artifact and Deploy to Staging
          caches:
            - composer
            - yarn
            - node
          script:
            # Move code to our working directory & fix ownerships
            - cp -a $BITBUCKET_CLONE_DIR/. /home/wp/code && chown -R wp:wp /home/wp/
            # Build Assets
            - su -c "export WP_ENV=staging; /home/wp/code/env/tools/initial-setup.sh" -s /bin/sh wp
            # Deploy to ElasticBeanstalk
            - su -c "export ENVIRONMENT='Staging'; /home/wp/code/env/build/build-artifact.sh" -s /bin/sh wp

definitions:
  caches:
    composer: /home/wp/.composer/cache
    yarn: /home/wp/.cache/yarn
