# Start with 4mation's base PHP 7.1.0 image
image: 4mation/wordpress:v5.3

pipelines:

  branches:
    release-*:
      - step:
          script:
            # Move code to our working directory
            - cp -a $BITBUCKET_CLONE_DIR/. /home/wp/code
            # Fix up SSH keys
            - cp -a ~/.ssh/. /home/wp/.ssh/ && chown -R wp:wp /home/wp/.ssh && chown wp:wp /opt/atlassian/pipelines/agent/data/id_rsa
            # Every time we push a commit it will re-setup the entire project
            - su -c "export WP_ENV=staging; ./env/tools/initial-setup.sh" -s /bin/sh wp
              ## Zip our artifact and deploy to S3
            - export ENVIRONMENT=staging; ./env/build/build-artifact.sh

          # cache our dependencies to speed up build time
          caches:
            - composer
            - node
            # we need our database to run selenium tests @todo get these working
          services:
            - database

    master:
        - step:
            script:
              ## Zip our artifact and deploy to S3
              - ./env/deploy/build-artifact.sh "production"

            # we need our database to run selenium tests
            services:
              - database


definitions:
  services:
    # we setup a database to spin up our wordpress
    database:
      image: mysql
      environment:
        MYSQL_DATABASE: 'awaba'
        MYSQL_ROOT_PASSWORD: 'awaba'
