# Same branch as our docker
image: php:7.1.0-apache

pipelines:
  default:
    - step:
        script:
          # Install depedencies
          - apt-get update -y -q && apt-get install git curl zip -y -q
          # Install composer
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          # Validate all PHP files are using correct syntax for our php version
          - composer global require --dev jakub-onderka/php-parallel-lint
          - export PATH=~/.composer/vendor/bin:$PATH
          - parallel-lint --exclude vendor .
          # check all packages can be installed
          - cp .env.example .env
          - ./env/deploy/deploy.sh
          # done
