# Same branch as our docker
image: php:7.1.0-apache

pipelines:
  default:
    - step:
        script:
          # Setup
          - cp .env.example .env
          # Setup yarn repos
          - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          # Install depedencies
          - apt-get update -y -q && apt-get install git curl zip yarn -y -q
          # Install composer
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          # Validate all PHP files are using correct syntax for our php version
          - composer global require --dev jakub-onderka/php-parallel-lint
          - export PATH=~/.composer/vendor/bin:$PATH
          - parallel-lint --exclude vendor .
          # Build our artifact
          - ./env/deploy/deploy.sh
          # done
