<?php

return [
	[
		'key' => 'field_5ad8302213595',
		'label' => 'Header',
		'name' => 'header',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],

	[
		'key' => 'field_5ad82fd0e878a',
		'label' => 'Cards',
		'name' => 'cards',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'collapsed' => 'field_5a67c4091898c',
		'min' => 0,
		'max' => 0,
		'layout' => 'row',
		'button_label' => 'Add Card',
		'sub_fields' => [
			[
				'key' => 'field_5ad83022134e8',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			],
			[
				'key' => 'field_5ad82fd0e88a4',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
			],
			[
				'key' => 'field_5ad842c788cc6',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'wysiwyg',
				'allow_null' => 0,
			],

			[
				'key' => 'field_5ad824848de1d',
				'label' => 'Buttons',
				'name' => 'buttons',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'collapsed' => 'field_5a67c4091898c',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add Button',
				'sub_fields' => [
					[
						'key' => 'field_5ad82ad5cc63c',
						'label' => 'Link URL',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5ad82ad5cc68b',
						'label' => 'Button Text',
						'name' => 'button_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '21',
					],
					[
						'key' => 'field_5ad82ad5cc6da',
						'label' => 'Link Type',
						'name' => 'link_type',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'choices' => [
							'same_window' => 'Same Window',
							'new_window' => 'New Window',
						],
						'default_value' => [
							0 => 'same_window',
						],
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					],
				],
			],
		],
	],
	[
		'key' => 'field_5ad83746a2d14',
		'label' => 'Buttons',
		'name' => 'buttons',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'collapsed' => 'field_5ad83747334fd',
		'min' => 0,
		'max' => 0,
		'layout' => 'table',
		'button_label' => 'Add Button',
		'sub_fields' => [
			[
				'key' => 'field_5ad83747334fd',
				'label' => 'Link URL',
				'name' => 'link',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5ad83747ea5be',
				'label' => 'Button Text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '21',
			],
			[
				'key' => 'field_5ad8375e474be',
				'label' => 'Link Type',
				'name' => 'link_type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'same_window' => 'Same Window',
					'new_window' => 'New Window',
				],
				'default_value' => [
					0 => 'same_window',
				],
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			],
		],
	],
	[
		'key' => 'field_5ad83b924bd58',
		'label' => 'Container Width',
		'name' => 'container_width',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'choices' => [
			'container' => 'Contained',
			'small-container ' => 'Small Contained',
			'full' => 'Full',
		],
		'default_value' => 'container',
		'allow_null' => 1,
		'multiple' => 0,
		'ui' => 1,
		'ajax' => 0,
		'return_format' => 'value',
		'placeholder' => '',
	],
	[
		'key' => 'field_59aa14f63ac44',
		'label' => 'Posts Per Row',
		'name' => 'posts_per_row',
		'type' => 'number',
		'instructions' => 'How many posts will be displayed in a row',
		'required' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => 3,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 2,
		'max' => 4,
		'step' => 1,
	],
	[
		'key' => 'field_5ad824848ddca',
		'label' => 'Background Colour',
		'name' => 'background_colour',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'choices' => App\COLOURS_CLASSES,
		// Remove Aubergine from options because the text color is this
		'default_value' => 'soft-blue',
		'allow_null' => 1,
		'multiple' => 0,
		'ui' => 1,
		'ajax' => 0,
		'return_format' => 'value',
		'placeholder' => '',
	],
];
