<?php
return [
    [
        'key' => 'field_5a3c7f158d467',
        'label' => 'Background Type',
        'name' => 'background_type',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'choices' => [
            'image' => 'Image',
            'parallax-image' => 'Parallax Image',
            'slider' => 'Slider',
        ],
        'default_value' => [
            0 => 'image',
        ],
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 1,
        'ajax' => 0,
        'return_format' => 'value',
        'placeholder' => '',
    ],
    [
        'key' => 'field_58e1bf55fb250',
        'label' => 'Background Image',
        'name' => 'background_image',
        'type' => 'image',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => [
	        [
		        [
			        'field' => 'field_5a3c7f158d467',
			        'operator' => '==',
			        'value' => 'image',
		        ],
	        ],

	        [
		        [
			        'field' => 'field_5a3c7f158d467',
			        'operator' => '==',
			        'value' => 'parallax-image',
		        ],
	        ]
        ],
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'return_format' => 'id',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
    ],
    [
        'key' => 'field_5a8a3b1958c58',
        'label' => 'Background Image Height',
        'name' => 'background_image_height',
        'type' => 'text',
        'required' => 1,
        'default_value' => 75,
        'instructions' => 'This is the % of the users screen height',
        'conditional_logic' => [
            [
                [
                    'field' => 'field_5a3c7f158d467',
                    'operator' => '==',
                    'value' => 'image',
                ],
            ],

	        [
		        [
			        'field' => 'field_5a3c7f158d467',
			        'operator' => '==',
			        'value' => 'parallax-image',
		        ],
	        ]

        ],
    ],
    [
        'key' => 'field_5a3c7f72d7ad3',
        'label' => 'Slider Alias',
        'name' => 'slider_alias',
        'type' => 'text',
        'instructions' => '',
        'conditional_logic' => [
            [
                [
                    'field' => 'field_5a3c7f158d467',
                    'operator' => '==',
                    'value' => 'slider',
                ],
            ],
        ],
        'required' => 1,
    ],
    [
        'key' => 'field_58e1bf94fb251',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_58e1bfa1fb252',
        'label' => 'Sub Title',
        'name' => 'sub_title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_5a44610d4538a',
        'label' => 'Show Scroll Helper',
        'name' => 'show_scroll_helper',
        'type' => 'true_false',
        'instructions' => '',
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ],
    [
        'key' => 'field_58e1bfb0fb253',
        'label' => 'Buttons',
        'name' => 'buttons',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'collapsed' => 'field_58e1bfc2fb255',
        'min' => 0,
        'max' => 3,
        'layout' => 'table',
        'button_label' => 'Add Button',
        'sub_fields' => [
            [
                'key' => 'field_58e1bfbbfb254',
                'label' => 'Link URL',
                'name' => 'link',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ],
            [
                'key' => 'field_58e1bfc2fb255',
                'label' => 'Button Text',
                'name' => 'button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '21',
            ],
            [
                'key' => 'field_58e1bfdffb256',
                'label' => 'Link Type',
                'name' => 'link_type',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'same_window' => 'Same Window',
                    'new_window' => 'New Window',
                ],
                'default_value' => [
                    0 => 'same_window',
                ],
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ],
        ],
    ],

	[
		'key' => 'field_5afd1285b804e',
		'label' => 'Container Width',
		'name' => 'container_width',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'choices' => [
			'container' => 'Contained',
			'small-container ' => 'Small Contained',
			'full' => 'Full',
		],
		'default_value' => 'full',
		'allow_null' => 1,
		'ui' => 1,
		'ajax' => 0,
		'return_format' => 'value',
		'placeholder' => '',
	],
];
