<?php

return [

	[
		'key' => 'field_5965c59398d5c',
		'label' => 'Gravity Form ID',
		'name' => 'gravity_form_id',
		'type' => 'number',
		'instructions' => 'This is the ID of the gravity form. It can be found on the gravity form view page.',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => '',
		'max' => '',
		'step' => '',
	],
	[
		'key' => 'field_5afe2d4ef01c4',
		'label' => 'Background Image',
		'name' => 'background_image',
		'type' => 'image',
		'instructions' => '',
		'required' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'return_format' => 'id',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	],
	[
		'key' => 'field_5ae8fbd411e81',
		'label' => 'Background Colour',
		'name' => 'background_colour',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'choices' => App\COLOURS_CLASSES,
		'default_value' => '',
		'allow_null' => 1,
		'multiple' => 0,
		'ui' => 1,
		'ajax' => 0,
		'return_format' => 'value',
		'placeholder' => '',
	],
];
