<?php

namespace App;

/**
 * Checks we have the add-on enabled
 */
if (!function_exists('acf_add_options_page')) {
	return;
}

const OPTION_PAGE_SLUG = 'mcgrath-settings';

const OPTION_PAGE_MAIN_LOGO = 'main_logo';
const OPTION_PAGE_ALT_LOGO = 'alt_logo';
const OPTION_PAGE_TC_PDF = 'terms_and_conditions';
const OPTION_PAGE_PHONE_NUMBER = 'phone_number';
const OPTION_PAGE_TELEPHONE = 'contact_telephone';
const OPTION_PAGE_PHONE_PREFIX = 'phone_prefix';
const OPTION_PAGE_PHONE_PREFIX_KEY = 'field_58e6ed96157df';
const OPTION_PAGE_CONTACT_EMAIL = 'contact_email';

const OPTION_PAGE_MAPS_KEY = 'maps_key';
const OPTION_PAGE_JOBADDER_KEY = 'jobadder_key';
const OPTION_PAGE_STREET = 'street';
const OPTION_PAGE_SUBURB = 'suburb';
const OPTION_PAGE_STATE = 'state';
const OPTION_PAGE_POSTCODE = 'postcode';
const OPTION_PAGE_OUR_LOCATIONS = 'our_location_column';
const OPTION_PAGE_HEADER_BANNER = 'header_banner';

// Contact card
const OPTION_PAGE_CONTACT_CARDS = 'contact_us_cards';
const OPTION_PAGE_CONTACT_PROFILE_PICTURE = 'profile_picture';
const OPTION_PAGE_CONTACT_TITLE = 'contact_title';
const OPTION_PAGE_CONTACT_SUB_TITLE = 'contact_sub_title';
const OPTION_PAGE_CONTACT_PHONE = 'contact_phone';
const OPTION_PAGE_CONTACT_DESCRIPTION = 'contact_description';

const OPTION_PAGE_CAMPAIGN_ENABLED = 'campaign_enabled';
const OPTION_PAGE_CAMPAIGN_IMAGE = 'campaign_image';
const OPTION_PAGE_CAMPAIGN_HEADER = 'campaign_header';
const OPTION_PAGE_CAMPAIGN_TITLE = 'campaign_title';
const OPTION_PAGE_CAMPAIGN_TEXT = 'campaign_text';
const OPTION_PAGE_CAMPAIGN_CTA_TITLE = 'campaign_cta_title';
const OPTION_PAGE_CAMPAIGN_CTA_LINK = 'campaign_cta_link';
const OPTION_PAGE_CAMPAIGN_CIRCLE_IMAGE = 'campaign_circle_image';

const OPTION_PAGE_FOOTER = 'footer';

$fields = [
	[
		'key' => 'field_58d33468f20a2',
		'label' => 'Branding',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'placement' => 'left',
		'endpoint' => 0,
	],
	[
		'key' => 'field_58d331f7fc040',
		'label' => 'Main Logo',
		'name' => OPTION_PAGE_MAIN_LOGO,
		'type' => 'image',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'return_format' => 'array',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_width' => '',
		'min_height' => '',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	],
	[
		'key' => 'field_58d33231fc041',
		'label' => 'Alt Logo',
		'name' => OPTION_PAGE_ALT_LOGO,
		'type' => 'image',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'return_format' => 'array',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_width' => '',
		'min_height' => '',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	],
	[
		'key' => 'field_58d33239fc042',
		'label' => 'Location',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'placement' => 'left',
		'endpoint' => 0,
	],
	[
		'key' => 'field_58d3344097cf3',
		'label' => 'Street',
		'name' => OPTION_PAGE_STREET,
		'type' => 'text',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_58d334c201f0b',
		'label' => 'Suburb',
		'name' => OPTION_PAGE_SUBURB,
		'type' => 'text',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_58d334cb01f0c',
		'label' => 'State',
		'name' => OPTION_PAGE_STATE,
		'type' => 'text',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_58d334d601f0d',
		'label' => 'Postcode',
		'name' => OPTION_PAGE_POSTCODE,
		'type' => 'text',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_58d33641ab18e',
		'label' => 'Contact',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'placement' => 'top',
		'endpoint' => 0,
	],
	[
		'key' => 'field_58d33709ab191',
		'label' => 'Email',
		'name' => OPTION_PAGE_CONTACT_EMAIL,
		'type' => 'email',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
	],
	[
		'key' => 'field_58d33659ab190',
		'label' => 'Telephone',
		'name' => OPTION_PAGE_TELEPHONE,
		'type' => 'text',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => OPTION_PAGE_PHONE_PREFIX_KEY,
		'label' => 'Phone Prefix',
		'name' => OPTION_PAGE_PHONE_PREFIX,
		'type' => 'text',
		'instructions' => 'Please enter the prefix to be used for all phone numbers.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '+61',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_58d3364aab18f',
		'label' => 'Type',
		'name' => 'contact_type',
		'type' => 'text',
		'instructions' => 'See here for clarification - https://schema.org/ContactPoint',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => 'customer service',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_58e3672642fd4',
		'label' => 'Vendor',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'placement' => 'top',
		'endpoint' => 0,
	],
	[
		'key' => 'field_5a6feda24dc97',
		'label' => 'Google Maps API Key',
		'name' => OPTION_PAGE_MAPS_KEY,
		'type' => 'text',
		'instructions' => 'Enter the google maps api key.',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_5a726536b6980',
		'label' => 'JobAdder Key',
		'name' => OPTION_PAGE_JOBADDER_KEY,
		'type' => 'text',
		'instructions' => 'Enter the JobAdder Key.',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	// Tab - Content
	[
		'key' => 'field_58fd6bc464bab',
		'label' => 'Content',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'placement' => 'left',
		'endpoint' => 0,
	],
	[
		'key' => 'field_592fbf7e5ae55',
		'label' => 'Footer Markup',
		'name' => OPTION_PAGE_FOOTER,
		'type' => 'text',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' =>
			'2017 McGrath Foundation. All Rights reserved.
         The McGrath Foundation is a registered charity in Austraila.',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_5a39f10af7194',
		'label' => 'Header Buttons',
		'name' => 'header_buttons',
		'type' => 'repeater',
		'instructions' => 'These appear in the header, to the right as extra prominent links for the user.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'collapsed' => '',
		'min' => 0,
		'max' => 3,
		'layout' => 'table',
		'button_label' => '',
		'sub_fields' => [
			[
				'key' => 'field_5a39f11ff7195',
				'label' => 'Button Title',
				'name' => 'button_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5a39f128f7196',
				'label' => 'Button Link',
				'name' => 'button_link',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'post_type' => [
					0 => 'page',
					1 => 'post',
				],
				'taxonomy' => [
				],
				'allow_null' => 0,
				'allow_archives' => 1,
				'multiple' => 0,
			],
			[
				'key' => 'field_5b0f4cc6822c2',
				'label' => 'Button Classes',
				'name' => 'button_classes',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => 'btn btn-light btn-xs',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
		],
	],
	[
		'key' => 'field_5a55504f1b218',
		'label' => 'Campaign Pop Up',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'placement' => 'left',
		'endpoint' => 0,
	],
	[
		'key' => 'field_5a555f9190578',
		'label' => 'Is the campaign active?',
		'name' => OPTION_PAGE_CAMPAIGN_ENABLED,
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	],
	[
		'key' => 'field_5a5591089fc33',
		'label' => 'Campaign Title',
		'name' => OPTION_PAGE_CAMPAIGN_TITLE,
		'type' => 'text',
		'instructions' => 'This should be unique for each campaign.',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => 'initial campaign',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_5a5550bc314da',
		'label' => 'Campaign Image',
		'name' => OPTION_PAGE_CAMPAIGN_IMAGE,
		'type' => 'image',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'return_format' => 'array',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_width' => '',
		'min_height' => '',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	],
	[
		'key' => 'field_5a5553b9db285',
		'label' => 'Campaign Header',
		'name' => OPTION_PAGE_CAMPAIGN_HEADER,
		'type' => 'text',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => 'Campaign Title',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_5a55546e5f7be',
		'label' => 'Content Text',
		'required' => 1,
		'name' => OPTION_PAGE_CAMPAIGN_TEXT,
		'type' => 'wysiwyg',
		'allow_null' => 0,
	],
	[
		'key' => 'field_5a55554cefc92',
		'label' => 'CTA Title',
		'name' => OPTION_PAGE_CAMPAIGN_CTA_TITLE,
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_5a555554249ad',
		'label' => 'CTA Link',
		'name' => OPTION_PAGE_CAMPAIGN_CTA_LINK,
		'type' => 'page_link',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'post_type' => [
			0 => 'page',
			1 => 'post',
		],
		'taxonomy' => [
		],
		'allow_null' => 0,
		'allow_archives' => 1,
		'multiple' => 0,
	],
	[
		'key' => 'field_5a55535f4ddfc',
		'label' => 'Circle Image',
		'name' => OPTION_PAGE_CAMPAIGN_CIRCLE_IMAGE,
		'type' => 'image',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'return_format' => 'array',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_width' => '',
		'min_height' => '',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	],
	[
		'key' => 'field_5aebdb256e929',
		'label' => 'Find Support',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'placement' => 'left',
		'endpoint' => 0,
	],
	[
		'key' => 'field_5aebd96d97918',
		'label' => 'Step',
		'name' => 'step',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'collapsed' => '',
		'min' => 0,
		'max' => 0,
		'layout' => 'row',
		'button_label' => '',
		'sub_fields' => [
			[
				'key' => 'field_5aebd9a097919',
				'label' => 'Name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5aebd9aa9791a',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			],
			[
				'key' => 'field_5af12aada429e',
				'label' => 'Main Content Title',
				'name' => 'main_content_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5aebd9bd9791b',
				'label' => 'Main Content',
				'name' => 'main_content',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			],
			[
				'key' => 'field_5aebdc3c26394',
				'label' => 'Buttons',
				'name' => 'buttons',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'collapsed' => 'field_5aebdbc896cc2',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add Button',
				'sub_fields' => [
					[
						'key' => 'field_5aebdbc896cc2',
						'label' => 'Link URL',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5aebdbc8de1aa',
						'label' => 'Button Text',
						'name' => 'button_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '21',
					],
					[
						'key' => 'field_5aebdbc935bd6',
						'label' => 'Link Type',
						'name' => 'link_type',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'choices' => [
							'same_window' => 'Same Window',
							'new_window' => 'New Window',
						],
						'default_value' => [
							0 => 'same_window',
						],
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					],
				],
			],
			[
				'key' => 'field_5afe164b711d3',
				'label' => 'Next Steps Title',
				'name' => 'next_steps_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5aebda029791d',
				'label' => 'Next Steps Row Count',
				'name' => 'next_steps_row_count',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => 2,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5aebda0e9791e',
				'label' => 'Next Steps',
				'name' => 'next_steps',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => '',
				'sub_fields' => [
					[
						'key' => 'field_5aebda189791f',
						'label' => 'Next Step Title',
						'name' => 'next_step_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5aebda2b97920',
						'label' => 'Next Step Image',
						'name' => 'next_step_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					],
					[
						'key' => 'field_5aebda3997921',
						'label' => 'Next Step Content',
						'name' => 'next_step_content',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 1,
					],
				],
			],
		],
	]
];


// Add in our option pages
acf_add_options_page([
	'page_title' => 'McGrath Settings',
	'menu_title' => 'McGrath Settings',
	'menu_slug' => OPTION_PAGE_SLUG,
	'position' => 70,
	'icon_url' => 'dashicons-admin-customizer'
]);

$fields = apply_filters('mcgrath/options-page-fields', $fields);

acf_add_local_field_group([
	'key' => 'group_58d331ebd36cc',
	'title' => 'Global Settings',
	'fields' => $fields,
	'location' => [
		[
			[
				'param' => 'options_page',
				'operator' => '==',
				'value' => OPTION_PAGE_SLUG,
			],
		],
	],
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
]);
