<?php

return [
	[
		'key' => 'field_5a13a80ad7924',
		'label' => 'Content',
		'name' => 'wysiwyg_content',
		'type' => 'wysiwyg',
		'allow_null' => 0,
	],

	[
		'key' => 'field_5a67c3aba4463',
		'label' => 'Header',
		'name' => 'header',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	],
	[
		'key' => 'field_5a67c421d5f2d',
		'label' => 'Buttons',
		'name' => 'buttons',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'collapsed' => 'field_5a67c4091898c',
		'min' => 0,
		'max' => 0,
		'layout' => 'table',
		'button_label' => 'Add Button',
		'sub_fields' => [
			[
				'key' => 'field_5a67c429074d2',
				'label' => 'Link URL',
				'name' => 'link',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'field_5a67c4091898c',
				'label' => 'Button Text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '21',
			],
			[
				'key' => 'field_5a67c4314f3bd',
				'label' => 'Link Type',
				'name' => 'link_type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'same_window' => 'Same Window',
					'new_window' => 'New Window',
				],
				'default_value' => [
					0 => 'same_window',
				],
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			],
		],
	],
	[
		'key' => 'field_5a3b79b18f2e8',
		'label' => 'Container Width',
		'name' => 'container_width',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'choices' => [
			'container' => 'Contained',
			'small-container ' => 'Small Contained',
			'full' => 'Full',
		],
		'default_value' => 'container',
		'allow_null' => 1,
		'multiple' => 0,
		'ui' => 1,
		'ajax' => 0,
		'return_format' => 'value',
		'placeholder' => '',
	],

	[
		'key' => 'field_58e6e1dd76a71',
		'label' => 'Background Colour',
		'name' => 'background_colour',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'choices' => App\COLOURS_CLASSES,
		'default_value' => '',
		'allow_null' => 1,
		'multiple' => 0,
		'ui' => 1,
		'ajax' => 0,
		'return_format' => 'value',
		'placeholder' => '',
	],
];
